/*
 *  © 2017 by Patrick Matthew Chan
 *  File: IngredientEditPanel.java
 *  Package: cpeprog
 *  Description: The IngredientEditPanel class.
 */
package unused;

import java.awt.event.ActionListener;

/**
 *
 * @author Patrick Matthew J. Chan
 */
public class IngredientEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form IngredientEditPanel
     */
    public IngredientEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQty = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIng = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        txtQty.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQty.setText("1");

        txtUnit.setText("pinch");

        txtIng.setColumns(20);
        txtIng.setLineWrap(true);
        txtIng.setRows(5);
        txtIng.setText("food");
        txtIng.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtIng);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jButton2.setText("X");
        jButton2.setToolTipText("Remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtIng;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables

    //---------------User Methods---------------------//
    //--BUTTON
    public void addActionListenerX(ActionListener l){
        jButton2.addActionListener(l);
    }
    public void setActionListenerX(ActionListener l){
        for (ActionListener l2 : jButton2.getActionListeners()) {
            jButton2.removeActionListener(l2);
        }
        jButton2.addActionListener(l);
    }
    public javax.swing.JButton xButton(){
        return jButton2;
    }
    
    //--TEXTS
    public String getQty(){
        return txtQty.getText().trim();
    }
    public String getUnit(){
        return txtUnit.getText().trim();
    }
    public String getIng(){
        return txtIng.getText().trim();
    }    
    
    public void setQty(String txt){
        txtQty.setText(txt);
    }
    public void setUnit(String txt){
        txtUnit.setText(txt);
    }
    public void setIng(String txt){
        txtIng.setLineWrap(true);
        txtIng.setWrapStyleWord(true);
        txtIng.setText(txt);
    }


}
