/*
 *  © 2017 by Patrick Matthew Chan
 *  File: AddButtonPanel.java
 *  Package: cpeprog
 *  Description: The AddButtonPanel class.
 */
package cpeprog;

import java.awt.event.ActionListener;

/**
 *
 * @author Patrick Matthew J. Chan
 */
public class AddButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddButtonPanel
     */
    public AddButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAdd = new javax.swing.JButton();

        butAdd.setText("+");
        butAdd.setToolTipText("Add Next");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    // End of variables declaration//GEN-END:variables
    
    //---------------User Methods---------------------//
    public void addActionListenerPlus(ActionListener l){
        butAdd.addActionListener(l);
    }
    public void setActionListenerPlus(ActionListener l){
        for (ActionListener l2 : butAdd.getActionListeners()) {
            butAdd.removeActionListener(l2);
        }
        butAdd.addActionListener(l);
    }
    public javax.swing.JButton plusButton(){
        return butAdd;
    }
    
}
